# Generated by Django 4.0.6 on 2022-07-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
