version: '3.3'
services:

  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

  django: &base_container
    image: blog_tms_django:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    command: |
      python manage.py runserver 0.0.0.0:8000
  worker:
    <<: *base_container
    ports: []
    command: |
      python manage.py rqworker default
#  bot:
#    <<: *base_container
#    ports: []
#    environment:
#      - DATABASE_HOST=postgres
#      - REDIS_HOST=redis
#      - BOT_TOKEN=5526476535:AAFuU4xZCxgb2yBPXAwpOW2msuLvtOGifDY
#      - CHAT_ID=1242849836
#    command: |
#      python manage.py run_bot
